version: '2.1'


services:

  reprova:
    container_name: reprova
    build: .
    image: gahag/reprova:v0.1
    environment:
      - REPROVA_TOKEN=d2fad245dd1d8a4f863e3f1c32bdada723361e6f63cfddf56663e516e47347bb
      - REPROVA_MONGO=mongo:27017
    ports:
    - 8080:8080
    depends_on:
    - mongo

  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
    - 27017:27017
    volumes:
    - ./db:/data/db
